spec_version = "1.0.0"
canonical_name = "atoms.convergent-systems.co/catalogs/schema-atoms"
version = "1.0.0-draft"
atom_type = "atoms.convergent-systems.co/catalogs"
authored_by = "ed25519:P6+CekZ4v8Y+h4AUvxnVoGc9scE4kwOn3Ee46/3P65Y="
created_at = "2026-07-30T22:51:21.656Z"

[signatures]
"ed25519:P6+CekZ4v8Y+h4AUvxnVoGc9scE4kwOn3Ee46/3P65Y=" = "M1AOqFL4uHEVdsRokJGIY147YU6mzbm0Y+Qt8QWsK08I57opEuEheDD32mEkhuH+Xe5a4GWxCVzC7infzibDAw=="

[body]
atom_types = []
canonical_domain = "schema-atoms.com"
catalog_name = "schema-atoms"
catalog_version = "1.0.0-draft"
github_url = "https://github.com/convergent-systems-co/schema-atoms"
implements_spec = "atoms-spec/v1"
license = "Apache-2.0"
pages_url = "https://schema-atoms.pages.dev"
rule_types = []
runtime_consumers = []
